# Generated by Django 5.1.15 on 2026-06-08 00:42

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateField(blank=True, null=True)),
                ('date_precision', models.CharField(blank=True, choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='', max_length=10)),
                ('title', models.CharField(max_length=512)),
                ('event_type', models.CharField(blank=True, default='', max_length=128)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.TextField(blank=True, default='')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('included_in_previsit', models.BooleanField(default=False)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timeline_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', 'source'], name='timeline_ev_user_id_be7b88_idx'), models.Index(fields=['user', 'included_in_previsit'], name='timeline_ev_user_id_68be05_idx')],
            },
        ),
    ]
