# Generated by Django 5.1.15 on 2026-06-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
