# Generated by Django 5.1.15 on 2026-06-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_timelineevent_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
