# Generated by Django 5.1.15 on 2026-06-08 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.IntegerField()),
                ('score_label', models.CharField(max_length=64)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('card_json', models.JSONField(blank=True, default=dict)),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('version', models.CharField(default='profile_v2', max_length=32)),
            ],
            options={
                'db_table': 'health_profiles',
            },
        ),
        migrations.CreateModel(
            name='HealthEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('result', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_evaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
