# Generated by Django 5.1.15 on 2026-06-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='digest_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='facts_digest',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
