# Generated by Django 5.1.15 on 2026-06-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthprofile_digest_meta_healthprofile_facts_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthevaluation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='healthevaluation',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
