# Generated by Django 5.1.15 on 2026-06-08 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex_or_gender', models.CharField(blank=True, default='', max_length=64)),
                ('occupation', models.CharField(blank=True, default='', max_length=255)),
                ('marital_status', models.CharField(blank=True, default='', max_length=64)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=64)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=64)),
                ('emergency_contact_relationship', models.CharField(blank=True, default='', max_length=128)),
                ('smoking_status', models.CharField(blank=True, default='', max_length=64)),
                ('alcohol_use', models.CharField(blank=True, default='', max_length=64)),
                ('exercise_level', models.CharField(blank=True, default='', max_length=64)),
                ('current_symptoms', models.TextField(blank=True, default='')),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('medications', models.JSONField(blank=True, default=list)),
                ('medical_history', models.JSONField(blank=True, default=list)),
                ('surgical_history', models.JSONField(blank=True, default=list)),
                ('family_history', models.JSONField(blank=True, default=list)),
                ('hospitalizations', models.JSONField(blank=True, default=list)),
                ('social_history', models.JSONField(blank=True, default=list)),
                ('story_answers', models.JSONField(blank=True, null=True)),
                ('ai_backfill_meta', models.JSONField(blank=True, null=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('health_linked_at', models.DateTimeField(blank=True, null=True)),
                ('avatar_path', models.CharField(blank=True, default='', max_length=1024)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
