# Generated by Django 5.1.15 on 2026-06-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_symptoms',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
