# Generated by Django 5.1.15 on 2026-06-18 19:47

import apps.common.encryption
from django.db import migrations


# The seven direct-identifier columns are altered to TEXT above, but existing
# rows still hold plaintext. These steps re-write each non-empty value as a
# Fernet token (and reverse them back to plaintext). We use RAW SQL — not the
# ORM — because the historical model already carries the encrypted field types
# (the AlterField ops run first), so going through the ORM would
# encrypt/decrypt the value a second time. Reading/writing the raw column lets
# us control the transform exactly. Both directions skip empty/NULL and values
# already in the target form, so they're safe on a fresh (no-rows) test DB and
# idempotent on re-run. (date_of_birth's column is now TEXT holding an ISO
# string; for a not-yet-migrated DB it may still be a SQL date — cast to text.)
_ALL_COLUMNS = [
    "first_name",
    "last_name",
    "mobile_phone",
    "emergency_contact_name",
    "emergency_contact_phone",
    "emergency_contact_relationship",
    "email",
    "date_of_birth",
]


def _select_sql():
    cols = ", ".join(f'"{c}"::text' for c in _ALL_COLUMNS)
    return f'SELECT id, {cols} FROM user_profiles'


def encrypt_existing(apps, schema_editor):
    from apps.common.encryption import _looks_encrypted, encrypt_str

    with schema_editor.connection.cursor() as cur:
        cur.execute(_select_sql())
        rows = cur.fetchall()
        for row in rows:
            pk, values = row[0], row[1:]
            updates = {}
            for col, val in zip(_ALL_COLUMNS, values):
                if val and not _looks_encrypted(val):
                    updates[col] = encrypt_str(val)
            if updates:
                set_clause = ", ".join(f'"{c}" = %s' for c in updates)
                cur.execute(
                    f'UPDATE user_profiles SET {set_clause} WHERE id = %s',
                    [*updates.values(), pk],
                )


def decrypt_existing(apps, schema_editor):
    from apps.common.encryption import _looks_encrypted, decrypt_str

    with schema_editor.connection.cursor() as cur:
        cur.execute(_select_sql())
        rows = cur.fetchall()
        for row in rows:
            pk, values = row[0], row[1:]
            updates = {}
            for col, val in zip(_ALL_COLUMNS, values):
                if val and _looks_encrypted(val):
                    updates[col] = decrypt_str(val)
            if updates:
                set_clause = ", ".join(f'"{c}" = %s' for c in updates)
                cur.execute(
                    f'UPDATE user_profiles SET {set_clause} WHERE id = %s',
                    [*updates.values(), pk],
                )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_add_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=apps.common.encryption.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=apps.common.encryption.EncryptedEmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact_name',
            field=apps.common.encryption.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=apps.common.encryption.EncryptedCharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact_relationship',
            field=apps.common.encryption.EncryptedCharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=apps.common.encryption.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=apps.common.encryption.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone',
            field=apps.common.encryption.EncryptedCharField(blank=True, default='', max_length=64),
        ),
        migrations.RunPython(encrypt_existing, decrypt_existing),
    ]
