# Generated by Django 5.1.15 on 2026-06-08 00:42

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('process_documents', 'Process Documents'), ('profile_evaluation', 'Profile Evaluation')], max_length=32)),
                ('document_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('priority', models.IntegerField(default=100)),
                ('attempts', models.IntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', max_length=255)),
                ('stage', models.CharField(blank=True, default='', max_length=128)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiJobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=8)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.aijob')),
            ],
            options={
                'db_table': 'ai_job_events',
                'ordering': ['at'],
            },
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['user', 'status'], name='ai_jobs_user_id_2c73f3_idx'),
        ),
    ]
