# Generated by Django 5.1.15 on 2026-06-10 12:37

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_fhir_path'),
        ('jobs', '0003_vector_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('doc_chunk', 'Doc Chunk'), ('fact', 'Fact'), ('timeline', 'Timeline')], max_length=16)),
                ('ref', models.CharField(blank=True, default='', max_length=64)),
                ('content', models.TextField()),
                ('vector', pgvector.django.vector.VectorField(dimensions=768)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'embeddings',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='emb_vec_hnsw', opclasses=['vector_cosine_ops']), models.Index(fields=['user'], name='embeddings_user_id_ffe914_idx')],
            },
        ),
    ]
