# Generated by Django 5.1.15 on 2026-06-18 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='aijob',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='BackfillAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_id', models.CharField(blank=True, max_length=64, null=True)),
                ('document_id', models.CharField(blank=True, max_length=64, null=True)),
                ('field_name', models.CharField(max_length=128)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField()),
                ('source', models.CharField(choices=[('ai_extraction', 'Ai Extraction'), ('manual_approval', 'Manual Approval'), ('system_import', 'System Import')], max_length=32)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_backfills', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backfill_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backfill_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
