import React, { useEffect, useRef, useState } from "react";
import {
  Animated,
  Easing,
  View,
  ScrollView,
  StyleSheet,
  Pressable,
  useWindowDimensions,
  NativeSyntheticEvent,
  NativeScrollEvent,
} from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { Ionicons } from "@expo/vector-icons";
import AsyncStorage from "@react-native-async-storage/async-storage";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { AuthStackParamList } from "../../navigation/authTypes";
import { PrimaryButton } from "../../components/ui/Primitives/PrimaryButton";
import { AppText } from "../../components/ui/Primitives/AppText";
import { spacing, typescale } from "../../theme/tokens";
import { createStyles } from "../../theme/createStyles";
import { useTheme } from "../../context/ThemeContext";

const WELCOME_KEY = "rivr_welcome_seen";

type Props = NativeStackScreenProps<AuthStackParamList, "Welcome">;

const panels = [
  {
    icon: "document-text-outline" as const,
    title: "All your records in one place",
    subtitle:
      "Upload documents, connect Apple Health, and build your complete health picture.",
  },
  {
    icon: "sparkles-outline" as const,
    title: "AI-powered insights",
    subtitle:
      "Get a personalized health score, smart recommendations, and an emergency card \u2014 all generated by AI.",
  },
  {
    icon: "share-outline" as const,
    title: "Share securely",
    subtitle:
      "Create expiring, links to share with doctors or family.",
  },
];

export function WelcomeScreen({ navigation }: Props) {
  const styles = useStyles();
  const { colors } = useTheme();
  const { width } = useWindowDimensions();
  const [page, setPage] = useState(0);
  const scrollRef = useRef<ScrollView>(null);

  // Per-panel animated values
  const anims = useRef(
    panels.map(() => ({
      iconScale: new Animated.Value(0.6),
      iconOpacity: new Animated.Value(0),
      titleOpacity: new Animated.Value(0),
      titleSlide: new Animated.Value(16),
      subtitleOpacity: new Animated.Value(0),
      subtitleSlide: new Animated.Value(16),
    }))
  ).current;

  const animatePanel = (index: number) => {
    const a = anims[index];
    // Reset values
    a.iconScale.setValue(0.6);
    a.iconOpacity.setValue(0);
    a.titleOpacity.setValue(0);
    a.titleSlide.setValue(16);
    a.subtitleOpacity.setValue(0);
    a.subtitleSlide.setValue(16);

    Animated.sequence([
      Animated.parallel([
        Animated.timing(a.iconOpacity, {
          toValue: 1,
          duration: 380,
          easing: Easing.out(Easing.cubic),
          useNativeDriver: true,
        }),
        Animated.timing(a.iconScale, {
          toValue: 1,
          duration: 380,
          easing: Easing.out(Easing.cubic),
          useNativeDriver: true,
        }),
      ]),
      Animated.parallel([
        Animated.timing(a.titleOpacity, {
          toValue: 1,
          duration: 340,
          easing: Easing.out(Easing.cubic),
          useNativeDriver: true,
        }),
        Animated.timing(a.titleSlide, {
          toValue: 0,
          duration: 340,
          easing: Easing.out(Easing.cubic),
          useNativeDriver: true,
        }),
      ]),
      Animated.parallel([
        Animated.timing(a.subtitleOpacity, {
          toValue: 1,
          duration: 260,
          easing: Easing.out(Easing.cubic),
          useNativeDriver: true,
        }),
        Animated.timing(a.subtitleSlide, {
          toValue: 0,
          duration: 260,
          easing: Easing.out(Easing.cubic),
          useNativeDriver: true,
        }),
      ]),
    ]).start();
  };

  // Animate the first panel on mount
  useEffect(() => {
    animatePanel(0);
    // Run only once so returning to this screen does not replay panel setup.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const finish = async () => {
    await AsyncStorage.setItem(WELCOME_KEY, "true");
    navigation.replace("Login");
  };

  const onScroll = (e: NativeSyntheticEvent<NativeScrollEvent>) => {
    const nextPage = Math.round(e.nativeEvent.contentOffset.x / width);
    if (nextPage !== page && nextPage >= 0 && nextPage < panels.length) {
      setPage(nextPage);
      animatePanel(nextPage);
    }
  };

  return (
    <LinearGradient colors={[colors.surface, colors.bg]} style={styles.root}>
      {/* Skip button — hidden on last panel */}
      {page < panels.length - 1 && (
        <Pressable
          accessible
          accessibilityRole="button"
          accessibilityLabel="Skip introduction"
          onPress={finish}
          style={({ pressed }) => [styles.skipBtn, pressed && { opacity: 0.5 }]}
        >
          <AppText style={styles.skipText}>Skip</AppText>
        </Pressable>
      )}

      <ScrollView
        ref={scrollRef}
        horizontal
        pagingEnabled
        showsHorizontalScrollIndicator={false}
        onMomentumScrollEnd={onScroll}
        scrollEventThrottle={16}
      >
        {panels.map((panel, i) => {
          const a = anims[i];
          return (
            <View key={i} style={[styles.panel, { width }]}>
              <View style={styles.content}>
                {/* Icon area */}
                <Animated.View
                  style={[
                    styles.iconWrap,
                    {
                      opacity: a.iconOpacity,
                      transform: [{ scale: a.iconScale }],
                    },
                  ]}
                >
                  <Ionicons
                    name={panel.icon}
                    size={80}
                    color={colors.teal}
                  />
                </Animated.View>

                {/* Title */}
                <Animated.View
                  style={{
                    opacity: a.titleOpacity,
                    transform: [{ translateY: a.titleSlide }],
                  }}
                >
                  <AppText style={styles.title}>{panel.title}</AppText>
                </Animated.View>

                {/* Subtitle */}
                <Animated.View
                  style={{
                    opacity: a.subtitleOpacity,
                    transform: [{ translateY: a.subtitleSlide }],
                  }}
                >
                  <AppText style={styles.subtitle}>{panel.subtitle}</AppText>
                </Animated.View>
              </View>

              {/* Get Started button on last panel */}
              {i === panels.length - 1 && (
                <Animated.View
                  style={[
                    styles.ctaWrap,
                    { opacity: a.subtitleOpacity },
                  ]}
                >
                  <PrimaryButton
                    label="Get Started"
                    onPress={finish}
                    tone="teal"
                    style={styles.cta}
                  />
                </Animated.View>
              )}
            </View>
          );
        })}
      </ScrollView>

      {/* Dot indicators */}
      <View style={styles.dots}>
        {panels.map((_, i) => (
          <View
            key={i}
            style={[
              styles.dot,
              { backgroundColor: i === page ? colors.teal : colors.border },
            ]}
          />
        ))}
      </View>
    </LinearGradient>
  );
}

const useStyles = createStyles((c) => StyleSheet.create({
  root: {
    flex: 1,
  },
  skipBtn: {
    position: "absolute",
    top: 60,
    right: spacing.xl,
    zIndex: 10,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
  },
  skipText: {
    fontSize: typescale.size.base,
    fontWeight: typescale.weight.medium,
    color: c.muted,
  },
  panel: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: spacing.xxl,
  },
  content: {
    alignItems: "center",
    gap: spacing.lg,
    maxWidth: 340,
  },
  iconWrap: {
    width: 120,
    height: 120,
    borderRadius: 30,
    backgroundColor: c.tealSoft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.md,
  },
  title: {
    fontSize: typescale.size.xxl,
    fontWeight: typescale.weight.bold,
    color: c.text,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: typescale.size.base,
    color: c.muted,
    textAlign: "center",
    lineHeight: typescale.size.base * typescale.lineHeight.relaxed,
  },
  ctaWrap: {
    width: "100%",
    maxWidth: 340,
    marginTop: spacing.xxl,
    paddingHorizontal: spacing.xl,
  },
  cta: {
    width: "100%",
  },
  dots: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: spacing.xs,
    paddingBottom: 60,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
}));
