# Generated by Django 5.1.15 on 2026-06-08 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('source_type', models.CharField(choices=[('file', 'File'), ('pdf', 'Pdf'), ('scanned_pdf', 'Scanned Pdf'), ('voice_note', 'Voice Note'), ('manual_input', 'Manual Input'), ('image', 'Image')], default='file', max_length=20)),
                ('pdf_path', models.CharField(blank=True, default='', max_length=1024)),
                ('fhir_path', models.CharField(blank=True, default='', max_length=1024)),
                ('summary_path', models.CharField(blank=True, default='', max_length=1024)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('content_json', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_type', 'manual_input')), fields=('user',), name='uniq_manual_input_doc_per_user')],
            },
        ),
    ]
