# Generated by Django 5.1.15 on 2026-06-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fhir_path',
        ),
    ]
