# Generated by Django 5.1.15 on 2026-06-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_fhir_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='detached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
