# Generated by Django 5.1.15 on 2026-06-08 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_type', models.CharField(choices=[('health_profile', 'Health Profile'), ('summary', 'Summary'), ('fhir', 'Fhir'), ('pdf', 'Pdf')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('max_views', models.IntegerField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('pin_hash', models.CharField(blank=True, default='', max_length=128)),
                ('pin_attempts', models.IntegerField(default=0)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('artifacts_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'share_packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharePackageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_items', to='documents.document')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shares.sharepackage')),
            ],
            options={
                'db_table': 'share_package_items',
                'constraints': [models.UniqueConstraint(fields=('package', 'document'), name='uniq_share_package_document')],
            },
        ),
    ]
