# Generated by Django 5.1.15 on 2026-06-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_delete_sharepackageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepackage',
            name='file_type',
            field=models.CharField(choices=[('health_profile', 'Health Profile')], max_length=20),
        ),
    ]
