# Generated by Django 5.1.15 on 2026-06-18 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_alter_sharepackage_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('resolved', 'Successfully resolved'), ('token_invalid', 'Invalid or revoked token'), ('expired', 'Share expired'), ('pin_mismatch', 'Wrong PIN'), ('pin_locked', 'PIN lockout active'), ('view_limit_exceeded', 'Max views reached')], max_length=32)),
                ('client_ip', models.CharField(db_index=True, max_length=45)),
                ('pin_attempt', models.IntegerField(blank=True, null=True)),
                ('views_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'share_access_logs',
            },
        ),
        migrations.AddField(
            model_name='sharepackage',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp when PIN lockout expires; None if not locked', null=True),
        ),
        migrations.AddConstraint(
            model_name='sharepackage',
            constraint=models.CheckConstraint(condition=models.Q(('pin_attempts__lte', 30)), name='pin_attempts_max_30'),
        ),
        migrations.AddField(
            model_name='shareaccesslog',
            name='share_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='shares.sharepackage'),
        ),
        migrations.AddIndex(
            model_name='shareaccesslog',
            index=models.Index(fields=['share_package', 'action', 'created_at'], name='share_acces_share_p_b22f74_idx'),
        ),
        migrations.AddIndex(
            model_name='shareaccesslog',
            index=models.Index(fields=['client_ip', 'created_at'], name='share_acces_client__c45936_idx'),
        ),
    ]
