# Generated by Django 5.1.15 on 2026-06-18 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubprocessorBAA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_name', models.CharField(max_length=255, unique=True)),
                ('service', models.CharField(blank=True, default='', max_length=512)),
                ('baa_signed_date', models.DateField()),
                ('baa_expires_at', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='pending', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'subprocessor_baas',
                'ordering': ['vendor_name'],
            },
        ),
    ]
